'use client';

import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import { useState } from 'react';

export default function DisclaimerCard() {
  const [isAccordionOpen, setIsAccordionOpen] = useState(false);

  const toggleAccordion = () => {
    setIsAccordionOpen(!isAccordionOpen);
  };

  return (
    <Card 
      title="Legal Disclaimer"
      footer={
        <Button 
          onClick={toggleAccordion}
          style={{width: "25%"}}>
          View
        </Button>
      }
    >
      <div className="mt-8 mb-4 text-xl font-semibold">
        <div style={{ width: '100%'}}>
          {isAccordionOpen && 
            (
              <div style={{ backgroundColor: '#000', padding: '15px', border: '1px solid #ddd', textAlign: 'left'}}>
                <p>This tool, <strong>Meducation 101</strong>, utilizes OpenAI's GPT-4 technology to generate SOAP notes intended for use in medical settings. The following points constitute the legal disclaimer associated with its use:</p><br />
                <p><strong>Auxiliary Tool Only:</strong> <strong>Meducation 101</strong> is designed to be an auxiliary tool for healthcare professionals. It is not a substitute for direct patient care or professional medical judgment. Users are responsible for reviewing and confirming the accuracy and relevance of the generated content in the context of each patient's specific medical situation.</p><br />
                <p><strong>No Medical Advice:</strong> The content generated by <strong>Meducation 101</strong> does not constitute medical advice, diagnosis, or treatment. Reliance on any information provided by this tool is solely at the user's own risk.</p><br />
                <p><strong>Limitation of Liability:</strong> <strong>HelloIT LLC</strong> (the developer of <strong>Meducation 101</strong>) is not liable for any errors, omissions, or inaccuracies in the content generated by Meducation 101, nor for any user's reliance on this content. The user assumes full responsibility for any decisions or actions taken based on the information provided by this tool.</p><br />
                <p><strong>Compliance with Laws and Regulations:</strong> Users are responsible for ensuring that their use of Meducation 101 complies with all applicable laws, regulations, and professional guidelines, including those pertaining to patient data privacy and security.</p><br />
                <p><strong>Indemnification:</strong> Users agree to indemnify and hold harmless HelloIT LLC and its affiliates, officers, agents, employees, and partners from any claim or demand, including reasonable attorneys' fees, arising from or related to the use of Meducation 101 or violation of this disclaimer.</p><br />
                <p><strong>Amendments and Updates:</strong> This disclaimer is subject to change, and users are advised to review it periodically. Continued use of Meducation 101 after any such changes constitutes acceptance of the new terms.</p><br />
                <p><strong>Governing Law:</strong> This disclaimer shall be governed by the laws of the State of Utah and the United States of America.</p><br />
                <p><strong>Acknowledgment:</strong> By using <strong>Meducation 101</strong>, users acknowledge that they have read, understood, and agreed to this disclaimer.</p><br />
                <p><strong>Contact Information:</strong> For any questions or concerns regarding this disclaimer, please contact <a href="https://buttonfortheinter.net">HelloIT LLC</a>.</p>
              </div>
            )
          }
        </div>
      </div>
    </Card>
  );
}
