export default function Disclaimer() {
    return (
    <div style={{ backgroundColor: '#f9f9f9', padding: '15px', border: '1px solid #ddd', textAlign: 'left'}}>
    {/* Insert your disclaimer text here */}
    <p>This tool, <strong>GPT SOAP Notes</strong>, utilizes OpenAI's GPT-4 technology to generate SOAP notes intended for use in medical settings. The following points constitute the legal disclaimer associated with its use:</p><br />

        <p><strong>Auxiliary Tool Only:</strong> <strong>GPT SOAP Notes</strong> is designed to be an auxiliary tool for healthcare professionals. It is not a substitute for direct patient care or professional medical judgment. Users are responsible for reviewing and confirming the accuracy and relevance of the generated content in the context of each patient's specific medical situation.</p><br />

        <p><strong>No Medical Advice:</strong> The content generated by <strong>GPT SOAP Notes</strong> does not constitute medical advice, diagnosis, or treatment. Reliance on any information provided by this tool is solely at the user's own risk.</p><br />

        <p><strong>Limitation of Liability:</strong> <strong>HelloIT LLC</strong> (the developer of <strong>GPT SOAP Notes</strong>) is not liable for any errors, omissions, or inaccuracies in the content generated by GPT SOAP Notes, nor for any user's reliance on this content. The user assumes full responsibility for any decisions or actions taken based on the information provided by this tool.</p><br />

        <p><strong>Compliance with Laws and Regulations:</strong> Users are responsible for ensuring that their use of GPT SOAP Notes complies with all applicable laws, regulations, and professional guidelines, including those pertaining to patient data privacy and security.</p><br />

        <p><strong>Indemnification:</strong> Users agree to indemnify and hold harmless HelloIT LLC and its affiliates, officers, agents, employees, and partners from any claim or demand, including reasonable attorneys' fees, arising from or related to the use of GPT SOAP Notes or violation of this disclaimer.</p><br />

        <p><strong>Amendments and Updates:</strong> This disclaimer is subject to change, and users are advised to review it periodically. Continued use of GPT SOAP Notes after any such changes constitutes acceptance of the new terms.</p><br />

        <p><strong>Governing Law:</strong> This disclaimer shall be governed by the laws of the State of Utah and the United States of America.</p><br />

        <p><strong>Acknowledgment:</strong> By using <strong>GPT SOAP Notes</strong>, users acknowledge that they have read, understood, and agreed to this disclaimer.</p><br />

        <p><strong>Contact Information:</strong> For any questions or concerns regarding this disclaimer, please contact <a href="https://buttonfortheinter.net">HelloIT LLC</a>.</p>
        </div>
)};